version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules

  blockchain:
    build:
      context: .
      dockerfile: apps/blockchain/Dockerfile
    ports:
      - "8545:8545"
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/blockchain:/app/apps/blockchain
      - /app/apps/blockchain/node_modules 