version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.vidgencraft.xyz
    restart: always

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/vidgencraft
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    restart: always

  blockchain:
    build:
      context: .
      dockerfile: apps/blockchain/Dockerfile.prod
    ports:
      - "8545:8545"
    environment:
      - NODE_ENV=production
    restart: always

  mongo:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - api
    restart: always

volumes:
  mongo-data: 